name: Labels

on: pull_request

jobs:
  apply-label:
    name: Label PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1.0.0

      - name: Sync Labels 
        uses: crazy-max/ghaction-github-labeler@v3
        with:
          yaml-file: .github/labels.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF} | tr '[:upper:]' '[:lower:]')"
        id: extract_branch

      - name: Apply Hotfix Label
        if: startsWith(steps.extract_branch.outputs.branch,'hotfix')
        uses: actions-ecosystem/action-add-labels@v1 
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: |
            hotfix

      - name: Apply Feature Label
        if: startsWith(steps.extract_branch.outputs.branch,'feature')
        uses: actions-ecosystem/action-add-labels@v1 
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: |
            feature
